dim_unidade = """--DIM UNIDADE
SELECT 
    DISTINCT
    SU.SU_ID AS "ID UNIDADE",
    SU.SU_NAME AS "UNIDADE",
    SU.SU_TYPE AS "TIPO"
FROM
    ITASYS.DBO.SALESUNIT SU
WHERE
    SU.STATUS_FLAG = 'S';"""

dim_supervisor = """--DIM SUPERVISOR
SELECT
    DISTINCT
    SUP.SP_ID AS "ID SUPERVISOR",
    CONCAT(SUP.SU_ID, RIGHT('000' + CAST(SPA.AREA_CODE AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
    SUP.SU_ID AS "ID UNIDADE",
    SPA.AREA_CODE AS "ID AREA",
    SUP.SP_NAME AS "SUPERVISOR"
FROM
    ITASYS.DBO.SALESPERSONS SUP
    INNER JOIN ITASYS.DBO.SALESPERSON_AREA SPA ON SUP.SP_ID = SPA.SP_ID
    INNER JOIN ITASYS.DBO.SALESUNIT SU ON SUP.SU_ID = SU.SU_ID
WHERE
	CAST(CONCAT(SUP.SU_ID, SPA.AREA_CODE) AS INT) <= 2000100
    AND CAST(CONCAT(SUP.SU_ID, SPA.AREA_CODE) AS INT) >= 00001
    AND SU.STATUS_FLAG = 'S'"""

dim_vendedor = """--DIM VENDEDOR
SELECT
    DISTINCT
    VEND.SU_ID AS "ID UNIDADE",
    CONCAT(VEND.SU_ID, RIGHT('000' + CAST(VEND.CODIGO_AREA AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
    VEND.CODIGO_AREA AS "ID AREA",
    VEND.NOME_VENDEDOR AS "VENDEDOR"
FROM
    ITALOAD.DBO.CARGA_VENDEDORES VEND
    INNER JOIN ITASYS.DBO.ORDER_INVOICED_OFF VEN ON VEND.SU_ID = VEN.UNIDADE
    INNER JOIN ITASYS.DBO.SALESUNIT SU ON VEN.UNIDADE = SU.SU_ID
WHERE
    VEN.ANOMES >= 201901
    AND CAST(CONCAT(VEND.SU_ID, VEND.CODIGO_AREA) AS INT) <= 2000100
    AND CAST(CONCAT(VEND.SU_ID, VEND.CODIGO_AREA) AS INT) >= 00001
    AND SU.STATUS_FLAG = 'S'"""

dim_cliente = """--DIM CLIENTE
SELECT 
    DISTINCT
    CLI.C_CODE AS "ID CLIENTE",
    CONCAT(VEN.UNIDADE, RIGHT('000' + CAST(CLI.AREA_MATRIZ AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
    VEN.UNIDADE AS "ID UNIDADE",
    CLI.AREA_MATRIZ AS "ID AREA",
    CLI.C_REGISTER_NUMBER AS "CNPJ",
    CLI.C_NAME AS "CLIENTE",
    CLI.ESTADO AS "ESTADO",
    CLI.CIDADE AS "CIDADE"
FROM
    ITASYS.DBO.CUSTOMERS CLI
    INNER JOIN ITASYS.DBO.ORDER_INVOICED_OFF VEN ON CLI.C_CODE = VEN.CODCLI
    INNER JOIN ITASYS.DBO.SALESUNIT SU ON VEN.UNIDADE = SU.SU_ID
WHERE
    VEN.ANOMES >= 201901
    AND CAST(CONCAT(VEN.UNIDADE, CLI.AREA_MATRIZ) AS INT) <= 2000100
    AND CAST(CONCAT(VEN.UNIDADE, CLI.AREA_MATRIZ) AS INT) >= 00001
    AND SU.STATUS_FLAG = 'S'"""

dim_produto = """--DIM PRODUTO
SELECT
    DISTINCT
    PROD.ITEM_CODE AS "ID PRODUTO",
    PROD.GRUPO AS "GRUPO",
    PROD.LINE AS "LINHA",
    PROD.FAMILY AS "FAMILIA",
    PROD.[DESCRIPTION] AS "PRODUTO"
FROM
    ITASYS.DBO.SALES_OBJECTIVE_REPORT_LAYOUT PROD
    INNER JOIN ITASYS.DBO.ORDER_INVOICED_OFF VEN ON PROD.ITEM_CODE = VEN.CODPRO
WHERE
    VEN.ANOMES >= 201901
    AND (PROD.LINE IS NOT NULL OR PROD.FAMILY IS NOT NULL)
GROUP BY
    PROD.ITEM_CODE,
    PROD.GRUPO,
    PROD.LINE,
    PROD.FAMILY,
    PROD.[DESCRIPTION];"""

fato_vendas = '''

-- FATO VENDAS
SELECT
    'FILIAL' AS TIPO,
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')) AS PERIODO,
    CONCAT(B.SU_ID, RIGHT('000' + CAST(D.AREA_MATRIZ AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
    A.[DATA] AS "DATA VENDA",
    A.NF AS "NOTA FISCAL",
    A.UNIDADE_FATURADORA AS "UNIDADE FATURADORA",
    A.CODCLI AS "ID CLIENTE",
    A.CODPRO AS "ID PRODUTO",
    A.LIN AS "LINHA",
    A.FAM AS "FAMILIA",
    A.ANOMES AS "ANO MES",
    A.CATEGORY AS "CATEGORIA",
    A.TIPOVEN AS "TIPO VENDA",
    A.TIPOCLI AS "TIPO CLIENTE",
    A.VOL_UNI AS "QUANTIDADE",
    B.SU_ID AS "ID UNIDADE",
    B.SU_NAME AS UNIDADE,
    D.AREA_MATRIZ AS "AREA",
    A.ANO AS "ANO",
    A.MES AS "MES",
    D.CANAL AS "CANAL",
    A.USO_MARCA AS USO,
    CASE 
        WHEN A.FAM = 'FERMENTO LIQUIDO' THEN SUM(A.VOL) * (0.2 / 0.33)
        WHEN A.FAM = 'LEVEDURA SECA' THEN SUM(A.VOL) * 3
        WHEN A.FAM = 'FI 10G' THEN SUM(A.VOL) * 3
        WHEN A.FAM = 'FI 500G' THEN SUM(A.VOL) * 3
        ELSE SUM(A.VOL)
    END AS VOLUME,
    SUM(A.FAT) AS FATURAMENTO
FROM
    ITASYS.DBO.ORDER_INVOICED_OFF A
    INNER JOIN ITASYS.DBO.SALESUNIT B ON A.UNIDADE = B.SU_ID AND B.STATUS_FLAG = 'S' AND B.SU_TYPE = 'FILIAL'
    INNER JOIN ITASYS.DBO.CUSTOMERS D ON A.CODCLI = D.C_CODE
WHERE 
    A.ANO >= 2022 AND A.FAM NOT IN ('LEVEDURA SECA', 'FERMENTO LIQUIDO') AND D.CANAL IS NOT NULL
GROUP BY 
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')),
    CONCAT(B.SU_ID, RIGHT('000' + CAST(D.AREA_MATRIZ AS VARCHAR(3)), 3)),
    A.[DATA],
    A.NF,
    A.UNIDADE_FATURADORA,
    A.UNIDADE,
    A.CODCLI,
    A.CODPRO,
    A.LIN,
    A.FAM,
    A.ANOMES,
    A.CATEGORY,
    A.TIPOVEN,
    A.TIPOCLI,
    A.VOL_UNI,
    B.SU_ID,
    B.SU_NAME,
    D.AREA_MATRIZ,
    A.ANO,
    A.MES,
    D.CANAL,
    A.USO_MARCA
HAVING 
    ANO >= 2019

UNION ALL

SELECT
    'REGIONAL' AS TIPO,
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')) AS PERIODO,
    CONCAT(B.SU_ID, RIGHT('000' + CAST(D.AREA_MATRIZ AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
    A.[DATA] AS "DATA VENDA",
    A.NF AS "NOTA FISCAL",
    A.UNIDADE_FATURADORA AS "UNIDADE FATURADORA",
    A.CODCLI AS "ID CLIENTE",
    A.CODPRO AS "ID PRODUTO",
    A.LIN AS "LINHA",
    A.FAM AS "FAMILIA",
    A.ANOMES AS "ANO MES",
    A.CATEGORY AS "CATEGORIA",
    A.TIPOVEN AS "TIPO VENDA",
    A.TIPOCLI AS "TIPO CLIENTE",
    A.VOL_UNI AS "QUANTIDADE",
    B.SU_ID AS "ID UNIDADE",
    B.SU_NAME AS UNIDADE,
    D.AREA_MATRIZ AS "AREA",
    A.ANO AS "ANO",
    A.MES AS "MES",
    D.CANAL AS "CANAL",
    A.USO_MARCA AS USO,
    CASE 
        WHEN A.FAM = 'FERMENTO LIQUIDO' THEN SUM(A.VOL) * (0.2 / 0.33)
        WHEN A.FAM = 'LEVEDURA SECA' THEN SUM(A.VOL) * 3
        WHEN A.FAM = 'FI 10G' THEN SUM(A.VOL) * 3
        WHEN A.FAM = 'FI 500G' THEN SUM(A.VOL) * 3
        ELSE SUM(A.VOL)
    END AS VOLUME,
    SUM(A.FAT) AS FATURAMENTO
FROM
    ITASYS.DBO.ORDER_INVOICED_OFF A
    INNER JOIN ITASYS.DBO.SALESUNIT B ON A.UNIDADE = B.SU_ID AND B.STATUS_FLAG = 'S' AND B.SU_TYPE = 'DISTRIBUIDOR'
    INNER JOIN ITASYS.DBO.CUSTOMER_TYPE C ON A.TIPOCLI = C.CT_CODE
    INNER JOIN ITASYS.DBO.CUSTOMERS D ON A.CODCLI = D.C_CODE
WHERE 
    A.ANO >= 2022 AND A.FAM NOT IN ('LEVEDURA SECA', 'FERMENTO LIQUIDO') AND D.CANAL IS NOT NULL
GROUP BY 
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')),
    CONCAT(B.SU_ID, RIGHT('000' + CAST(D.AREA_MATRIZ AS VARCHAR(3)), 3)),
    A.[DATA],
    A.NF,
    A.UNIDADE_FATURADORA,
    A.UNIDADE,
    A.CODCLI,
    A.CODPRO,
    A.LIN,
    A.FAM,
    A.ANOMES,
    A.CATEGORY,
    A.TIPOVEN,
    A.TIPOCLI,
    A.VOL_UNI,
    B.SU_ID,
    B.SU_NAME,
    D.AREA_MATRIZ,
    A.ANO,
    A.MES,
    D.CANAL,
    A.USO_MARCA
HAVING 
    ANO >= 2019

UNION ALL

SELECT
    'REGIONAL' AS TIPO,
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')) AS PERIODO,
    CONCAT(B.SU_ID, RIGHT('000' + CAST(B.AREA_MATRIZ AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
    A.[DATA] AS "DATA VENDA",
    A.NF AS "NOTA FISCAL",
    A.UNIDADE_FATURADORA AS "UNIDADE FATURADORA",
    A.CODCLI AS "ID CLIENTE",
    E.CODPRO AS "ID PRODUTO",
    E.LIN AS "LINHA",
    E.FAM AS "FAMILIA",
    A.ANOMES AS "ANO MES",
    E.CATEGORY AS "CATEGORIA",
    E.TIPOVEN AS "TIPO VENDA",
    E.TIPOCLI AS "TIPO CLIENTE",
    A.VOL_UNI AS "QUANTIDADE",
    C.SU_ID AS "ID UNIDADE",
    C.SU_NAME AS UNIDADE,
    B.AREA_MATRIZ AS "AREA",
    A.ANO AS "ANO",
    A.MES AS "MES",
    B.CANAL AS "CANAL",
    E.USO_MARCA AS USO,
    CASE 
        WHEN E.FAM = 'FERMENTO LIQUIDO' THEN SUM(A.VOL) * (0.2 / 0.33)
        WHEN E.FAM = 'LEVEDURA SECA' THEN SUM(A.VOL) * 3
        WHEN E.FAM = 'FI 10G' THEN SUM(A.VOL) * 3
        WHEN E.FAM = 'FI 500G' THEN SUM(A.VOL) * 3
        ELSE SUM(A.VOL)
    END AS VOLUME,
    SUM(A.FAT) AS FATURAMENTO
FROM
    ITASYS.DBO.ORDERINDUSTRIES A
    INNER JOIN ITASYS.DBO.CUSTOMERS B ON A.CODCLI = B.C_CODE
    INNER JOIN ITASYS.DBO.SALESUNIT C ON B.SU_ID = C.SU_ID
    INNER JOIN ITASYS.DBO.SALES_OBJECTIVE_REPORT_LAYOUT D ON A.CODPRO = D.ITEM_CODE
    INNER JOIN ITASYS.DBO.ORDER_INVOICED_OFF E ON A.CODCLI = E.CODCLI
WHERE 
    A.ANO >= 2019 AND A.ANO <= 2021
GROUP BY 
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')),
    CONCAT(B.SU_ID, RIGHT('000' + CAST(B.AREA_MATRIZ AS VARCHAR(3)), 3)),
    A.[DATA],
    A.NF,
    A.UNIDADE_FATURADORA,
    E.UNIDADE,
    A.CODCLI,
    E.CODPRO,
    E.LIN,
    E.FAM,
    A.ANOMES,
    E.CATEGORY,
    E.TIPOVEN,
    E.TIPOCLI,
    A.VOL_UNI,
    C.SU_ID,
    C.SU_NAME,
    B.AREA_MATRIZ,
    A.ANO,
    A.MES,
    B.CANAL,
    E.USO_MARCA

UNION ALL

SELECT
    'REGIONAL' AS TIPO,
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')) AS PERIODO,
    CONCAT(B.SU_ID, RIGHT('000' + CAST(D.AREA_MATRIZ AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
    A.[DATA] AS "DATA VENDA",
    A.NF AS "NOTA FISCAL",
    A.UNIDADE_FATURADORA AS "UNIDADE FATURADORA",
    A.CODCLI AS "ID CLIENTE",
    A.CODPRO AS "ID PRODUTO",
    A.LIN AS "LINHA",
    A.FAM AS "FAMILIA",
    A.ANOMES AS "ANO MES",
    A.CATEGORY AS "CATEGORIA",
    A.TIPOVEN AS "TIPO VENDA",
    A.TIPOCLI AS "TIPO CLIENTE",
    A.VOL_UNI AS "QUANTIDADE",
    B.SU_ID AS "ID UNIDADE",
    B.SU_NAME AS UNIDADE,
    D.AREA_MATRIZ AS "AREA",
    A.ANO AS "ANO",
    A.MES AS "MES",
    D.CANAL AS "CANAL",
    A.USO_MARCA AS USO,
    CASE 
        WHEN A.FAM = 'FERMENTO LIQUIDO' THEN SUM(A.VOL) * (0.2 / 0.33)
        WHEN A.FAM = 'LEVEDURA SECA' THEN SUM(A.VOL) * 3
        WHEN A.FAM = 'FI 10G' THEN SUM(A.VOL) * 3
        WHEN A.FAM = 'FI 500G' THEN SUM(A.VOL) * 3
        ELSE SUM(A.VOL)
    END AS VOLUME,
    SUM(A.FAT) AS FATURAMENTO
FROM
    ITASYS.DBO.ORDER_INVOICED_OFF A
    INNER JOIN ITASYS.DBO.SALESUNIT B ON A.UNIDADE = B.SU_ID AND B.STATUS_FLAG = 'S' AND B.SU_TYPE = 'DISTRIBUIDOR'
    INNER JOIN ITASYS.DBO.CUSTOMER_TYPE C ON A.TIPOCLI = C.CT_CODE
    INNER JOIN ITASYS.DBO.CUSTOMERS D ON A.CODCLI = D.C_CODE
WHERE 
    A.ANO >= 2022 AND A.FAM IN ('LEVEDURA SECA', 'FERMENTO LIQUIDO') AND D.CANAL IS NOT NULL
GROUP BY 
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')),
    CONCAT(B.SU_ID, RIGHT('000' + CAST(D.AREA_MATRIZ AS VARCHAR(3)), 3)),
    A.[DATA],
    A.NF,
    A.UNIDADE_FATURADORA,
    A.UNIDADE,
    A.CODCLI,
    A.CODPRO,
    A.LIN,
    A.FAM,
    A.ANOMES,
    A.CATEGORY,
    A.TIPOVEN,
    A.TIPOCLI,
    A.VOL_UNI,
    B.SU_ID,
    B.SU_NAME,
    D.AREA_MATRIZ,
    A.ANO,
    A.MES,
    D.CANAL,
    A.USO_MARCA
HAVING 
    ANO >= 2022
'''

fato_volume_orcado = """
-- FATO VOLUME ORÇADO

SELECT 
    SU_ID AS "CODIGO UNIDADE",
    ASOD_YEAR AS "ANO ORCADO",
    ASOD_MONTH AS "MES ORCADO",
    LINE AS "LINHA",
    FAMILY AS "FAMILIA",
    CATEGORY AS "CATEGORIA",
    SUM(CASE 
            WHEN FAMILY = 'FERMENTO LIQUIDO' THEN BUD_VOLUME * (0.2 / 0.33)
            WHEN FAMILY = 'LEVEDURA SECA' THEN BUD_VOLUME * 3
            WHEN FAMILY = 'FI 10G' THEN BUD_VOLUME * 3
            WHEN FAMILY = 'FI 500G' THEN BUD_VOLUME * 3
            ELSE BUD_VOLUME
        END) AS "BUDGET VOLUME",
    SUM(BUD_FAT) AS "BUDGET FATURAMENTO",
    SUM(CASE 
            WHEN FAMILY = 'FERMENTO LIQUIDO' THEN OBJ_VOLUME * (0.2 / 0.33)
            WHEN FAMILY = 'LEVEDURA SECA' THEN OBJ_VOLUME * 3
            WHEN FAMILY = 'FI 10G' THEN OBJ_VOLUME * 3
            WHEN FAMILY = 'FI 500G' THEN OBJ_VOLUME * 3
            ELSE OBJ_VOLUME
        END) AS "OBJETIVO VOLUME",
	SUM(OBJ_FAT) AS "OBJETIVO FATURAMENTO",
    SUM(CASE 
            WHEN FAMILY = 'FERMENTO LIQUIDO' THEN CAMP_VOL * (0.2 / 0.33)
            WHEN FAMILY = 'LEVEDURA SECA' THEN CAMP_VOL * 3
            WHEN FAMILY = 'FI 10G' THEN CAMP_VOL * 3
            WHEN FAMILY = 'FI 500G' THEN CAMP_VOL * 3
            ELSE CAMP_VOL
        END) AS "CAMPANHA VOLUME",
    SUM(CAMP_FAT) AS "CAMPANHA FATURAMENTO",
    C_CODE AS "ID CLIENTE"
FROM 
    ITASYS.DBO.CURRENT_BROKEN_OBJECTIVE_HISTORY 
WHERE
    ASOD_YEAR >= 2022
GROUP BY
    SU_ID,
    ASOD_YEAR,
    ASOD_MONTH,
    LINE,
    FAMILY,
    CATEGORY,
    C_CODE

UNION ALL

SELECT 
    SU_ID AS "CODIGO UNIDADE",
    ASOD_YEAR AS "ANO ORCADO",
    ASOD_MONTH AS "MES ORCADO",
    LINE AS "LINHA",
    FAMILY AS "FAMILIA",
    CATEGORY AS "CATEGORIA",
    SUM(CASE 
            WHEN FAMILY = 'FERMENTO LIQUIDO' THEN BUD_VOLUME * (0.2 / 0.33)
            WHEN FAMILY = 'LEVEDURA SECA' THEN BUD_VOLUME * 3
            WHEN FAMILY = 'FI 10G' THEN BUD_VOLUME * 3
            WHEN FAMILY = 'FI 500G' THEN BUD_VOLUME * 3
            ELSE BUD_VOLUME
        END) AS "BUDGET VOLUME",
    SUM(BUD_FAT) AS "BUDGET FATURAMENTO",
    SUM(CASE 
            WHEN FAMILY = 'FERMENTO LIQUIDO' THEN OBJ_VOLUME * (0.2 / 0.33)
            WHEN FAMILY = 'LEVEDURA SECA' THEN OBJ_VOLUME * 3
            WHEN FAMILY = 'FI 10G' THEN OBJ_VOLUME * 3
            WHEN FAMILY = 'FI 500G' THEN OBJ_VOLUME * 3
            ELSE OBJ_VOLUME
        END) AS "OBJETIVO VOLUME",
	SUM(OBJ_FAT) AS "OBJETIVO FATURAMENTO",
    SUM(CASE 
            WHEN FAMILY = 'FERMENTO LIQUIDO' THEN CAMP_VOL * (0.2 / 0.33)
            WHEN FAMILY = 'LEVEDURA SECA' THEN CAMP_VOL * 3
            WHEN FAMILY = 'FI 10G' THEN CAMP_VOL * 3
            WHEN FAMILY = 'FI 500G' THEN CAMP_VOL * 3
            ELSE CAMP_VOL
        END) AS "CAMPANHA VOLUME",
    SUM(CAMP_FAT) AS "CAMPANHA FATURAMENTO",
    C_CODE AS "ID CLIENTE"
FROM 
    ITASYS.DBO.CURRENT_BROKEN_OBJECTIVE 
GROUP BY
    SU_ID,
    ASOD_YEAR,
    ASOD_MONTH,
    LINE,
    FAMILY,
    CATEGORY,
    C_CODE
ORDER BY
    ASOD_YEAR, ASOD_MONTH;

"""

fato_churn = """
-- FATO CHURN

SELECT
    UPPER(FORMAT(CONVERT(DATE, CONVERT(VARCHAR(6), A.ANOMES) + '01', 112), 'MMM/yy', 'pt-BR')) AS PERIODO,
	CONCAT(A.ANO, '/', RIGHT('00' + CAST(A.MES AS VARCHAR(2)), 2), '/01') AS "DATA",
    CONCAT(A.SU_ID, RIGHT('000' + CAST(A.AREA AS VARCHAR(3)), 3)) AS "UNIDADE AREA",
	A.ANO AS ANO,
	A.MES AS MES,
	A.SU_ID AS "ID UNIDADE",
	A.AREA AS AREA,
	A.CODCLI AS "ID CLIENTE",
	A.C_NAME AS CLIENTE,
	A.CLIENTE AS "ID - CLIENTE"
FROM
	RP1.DBO.COBERTURA AS A
WHERE
	FAT = 0
"""